import Head from "next/head"
import { 
  BsFillMoonStarsFill 
} from 'react-icons/bs'
import { 
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillInstagram, 
  AiFillDatabase, 
  AiOutlineCloudServer,
  AiFillHtml5,
 } from 'react-icons/ai'
import { 
  SiExpress, 
  SiReact, 
  SiJavascript,
  SiCsswizardry
 } from 'react-icons/si'
import { 
  DiMongodb,
  DiNpm
 } from 'react-icons/di'
import Image from "next/image"
import fauzan from "../public/fauzan.png"
import design from '../public/icons8-nodejs-480.png'
import code from '../public/mongodb.png'
import consulting1 from '../public/icons8-html-5-480.png'
import consulting2 from '../public/icons8-css-64.png'
import consulting3 from '../public/icons8-javascript.gif'
import web1 from '../public/pesan-makanan.png'
import web2 from '../public/multi-role.png'
import web3 from '../public/blog-post.png'
import web4 from '../public/photo-sharing.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode ] = useState(false)
  const bukaTabBaruPhotoSharing = () => {
    window.open("https://odd-gold-gecko-cuff.cyclic.app/login");
  };
  const bukaTabBaruKasirApp = () => {
    window.open("https://kasir-app-five.vercel.app/");
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Fauzan Octhory Portofolio</title>
        <meta name='description' content='Generated By creation' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900">
        <section className="">
          <nav className="py-10 mb-2 flex justify-between">
            <h1 className="dark:text-gray-200 text-xl font-burtons">FauzanPorto</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-gray-200 sm:ml-4" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-400 to bg-cyan-500 text-white px-4 py-2 rounded-md ml-8 sm:ml-2" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-2">   
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Fauzan Octhory</h2>
            <h3 className="dark:text-gray-200 text-2xl py-2 md:text-3xl">Just a Learner Developer</h3>
            <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full overflow-hidden w-80 h-80 mt-5 md:w-60 md:h-60">
              <Image src={fauzan} className="px-10" alt="fauzan" fill style={{objectFit: "cover"}}/>
            </div>
            <p className="dark:text-gray-200 text-md py-5 leading-8 text-gray-800">
              Born in Pekanbaru Riau Indonesia I am a Full Stack Web Developer
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
          <a href={""}>
            <AiFillTwitterCircle />
            </a>
            <a href={"https://www.linkedin.com/in/fauzan-octhory-lukfi-8b734219a"}>
              <AiFillLinkedin />
            </a>
            <a href={"https://www.instagram.com/fauzanocthory/"}>
              <AiFillInstagram />
            </a>
          </div>
        </section>

{/* SKILLS */}
        <section>
          <div className="text-1xl text-center my-10">
            <h3 className="text-4xl py-1 text-teal-500 underline underline-offset-8">Skills</h3>
            <p className="dark:text-gray-200 text-md py-2 leading-8 text-gray-700">
              Saya pernah merancang atau membuat beberapa aplikasi web dengan menggunakan beberapa framework dan bahasa pemrograman seperti dibawah ini  
            </p>
          </div>
          
          <div className="lg:flex sm:flex-col gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} alt="Logo" width={100} height={100}  className="m-auto"/>
              <h3 className="dark:text-gray-900 text-lg font-medium pt-8 pb-2 text-teal-600 underline">Node JS</h3>
              <p className="dark:text-gray-900 py-2">
                Saya memiliki sedikit pengetahuan tentang NodeJS mengerjakan beberapa 
                aplikasi web dengan bantuan framework seperti ExpressJS, ReactJS, dan 
                framework-framework lainnya yang saya butuhkan ketika mengembangkan aplikasi
              </p>
              <div className="text-4xl flex justify-center gap-7 py-6 text-gray-600">
                <SiExpress />
                <SiReact />
                <DiNpm />
              </div>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} alt="" width={100} height={100}  className="m-auto"/>
              <h3 className="dark:text-gray-900 text-lg font-medium pt-8 pb-2 text-teal-600 underline">MongoDB</h3>
              <p className="dark:text-gray-900 py-2">
                MongoDb merupakan database yang orientasi nya berdasarkan objek bukan relasi 
                seperti Mysql dalam mengembangkan beberapa aplikasi web saya pernah menggunakan 
                MongoDb untuk mengatur data-data pada aplikasi yang saya kembangkan
              </p>
              <div className="text-4xl flex justify-center gap-7 py-6 text-gray-600">
                <AiFillDatabase />
                <DiMongodb />
                <AiOutlineCloudServer />
              </div>
            </div>
            
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex">
                <Image src={consulting1} alt="" width={50} height={50}  className="m-auto flex-auto"/>
                <Image src={consulting2} alt="" width={50} height={50}  className="m-auto flex-auto"/>
                <Image src={consulting3} alt="" width={50} height={50}  className="m-auto flex-auto"/>
              </div>
              <h3 className="dark:text-gray-900 text-lg font-medium pt-8 pb-2 text-teal-600 underline">MongoDB</h3>
              <p className="dark:text-gray-900 py-2">
                HTML, CSS, JS merupakan Markup Language bisa disebut bahasa pemorgraman atau tidak terserah yang baca. Bahasa ini merupakan dasar dari programmer tepatnya pada bidang web developer
              </p>
              <div className="text-4xl flex justify-center gap-7 py-6 text-gray-600">
                <AiFillHtml5 /> 
                <SiCsswizardry />
                <SiJavascript />
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="text-center">
            <h3 className="text-4xl py-1 text-teal-500 underline underline-offset-8">Portofolio</h3>
            <p className="dark:text-gray-200 text-md py-2 leading-8 text-gray-800">
              Inilah project-project yang pernah saya buat, ya walaupun belum kelihatan professional tapi jadilah dari pada engga hehe
            </p>
            <h4>
                Jika anda ingin melihat-lihat silahkan klik gambar dibawah
                <br/>Username : root
                <br/>password : root
            </h4>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div  className="basis-1/3 flex-1">
              <Image onClick={bukaTabBaruKasirApp} alt="" src={web1} className="rounded-lg object-cover hover:animate-pulse hover:cursor-pointer" width={'0.1'} height={'0.1'}/>
              <h3 className="text-center text-2xl text-teal-600 p-4">
                Aplikasi Pemesanan <br /> Makanan Pada Restoran/Warung Makan dengan menggunakan ReactJS, ReactBootstrap, SweetAllert dan Axios
              </h3>
            </div>
            <div  className="basis-1/3 flex-1">
              <Image alt="" src={web2} className="rounded-lg object-cover hover:animate-pulse hover:cursor-pointer" width={'0.1'} height={'0.1'}/>
              <h3 className="text-center text-2xl text-teal-600 p-4">
                Aplikasi CRUD <br /> dengan menerapkan Login Multi Role dengan menggunakan NodeJS, ExpressJS, ReactJS dan MySQL
              </h3>
            </div>
            <div  className="basis-1/3 flex-1">
              <Image alt="" src={web3} className="rounded-lg object-cover hover:animate-pulse hover:cursor-pointer" width={'0.1'} height={'0.1'}/>
              <h3 className="text-center text-2xl text-teal-600 p-4">
                Aplikasi Blog Post <br /> dengan menerapkan MERN Stack ~ MongoDB, ExpressJS, ReactJS, NodeJS 
              </h3>
            </div>
            <div  className="basis-1/3 flex-1">
              <Image onClick={bukaTabBaruPhotoSharing} alt="" src={web4} className="rounded-lg object-cover hover:animate-pulse hover:cursor-pointer" width={'0.1'} height={'0.1'} layout={"responsive"}/>
              <h3 className="text-center text-2xl text-teal-600 p-4">
                Aplikasi Photo Sharing App <br /> dengan menggunakan NextJS, ExpressJS dan MariaDB
              </h3>
            </div>
          </div>

        </section>
      </main>
    </div>
  )
}